### ISSUE TITLE
Create a github action that install Gazebo releases on Linux

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/setup-gazebo#1]
Following the setup-ros repository inputs, the first step to build in this repository is the ability to run a GitHub action that install Gazebo releases on a given Linux platform:

See https://github.com/ros-tooling/setup-ros/blob/master/action.yml#L19-L37
```yaml
  required-ros-distributions:
    description: |
      List of binary ROS distributions to be installed.

      On Ubuntu, this installs the desktop variant for the given distribution.
      On Windows, this downloads and extracts the binaries for the given distribution.
      This parameter is ignored on macOS.

      Allowed ROS distributions
      - "" (no value) - no ROS binary installation
      - noetic
      - humble
      - iron
      - jazzy
      - rolling

      Multiple values can be passed using a whitespace delimited list
      "noetic humble".
```

Lets try to build the same for `required-gazebo-distributions`.

For the installation some hints:
 - Install the packages.osrfoundation.org repository
 - Use the packages named `gz-${distribution}` to get everything installed (i.e gz-harmonic)
 - Ignore the new vendor packages in Jazzy
 - By now: use Ubuntu Focal for Citadel, Garden and Fortress. use Ubuntu Jammy for Harmonic. These are the gazebo distributions supported initially.
 

For testing, we can probably mirroring what is being done in:
https://github.com/ros-tooling/setup-ros/blob/master/.github/workflows/test.yml#L97-L158
