### ISSUE TITLE
Support to install ros_gz when using also ros-setup

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/setup-gazebo#62]
An optional support for this action could be the addition of the necessary logic to install the ROS bridge (`ros_gz`). The idea could be that a user create an action something like:

```yaml
  runs-on: ubuntu:24.04
  steps:
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: jazzy
    -  uses: gazebo-tooling/setup-gazebo@v0.1.0
       with:
         required-gazebo-distributions: harmonic
         install-ros-bridge: true
```

And this action takes care of installing the `ros_gz`  bridge according to the documentation: https://gazebosim.org/docs/latest/ros_installation/#installing-the-default-gazebo-ros-pairing

The list of combinations is well detailed in the Gazebo/ROS documentation https://gazebosim.org/docs/latest/ros_installation/#summary-of-compatible-ros-and-gazebo-combinations. In a first step, we can support the green checks from the table, the "recommended combinations" since they require no special option and are supported from the ROS repository out of the box (mostly apt-get install `ros-$ROS_DISTRO-ros-gz`). In a second step we can support the combinations that are marked as "Posible use with caution". These options involved the use of packages from packages.osrfoundation.org (mainly to use `ros-$ROS_DISTRO-ros_gz$GAZEBO_DISTRO`).
